spring:
  application:
    name: RelaxMap-back

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update

storage:
  upload-dir: uploads/images
  allowed-mime-types:
    - image/png
    - image/jpeg
  max-file-size: 1MB

server:
  port: 8080