spring:
  application:
    name: RelaxMap-back

#  Temporary url
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: update

storage:
  upload-dir: uploads/images
  allowed-mime-types:
    - image/png
    - image/jpeg
  max-file-size: 1MB